language: objective-c
xcode_project: AlamofireSwiftyJSON.xcodeproj
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
xcode_scheme: AlamofireSwiftyJSON

before_install:
#  - brew update
  - brew install swiftlint
#  - brew install carthage
#  - gem install cocoapods
install: carthage bootstrap

script:
  - xctool -scheme 'AlamofireSwiftyJSON iOS' -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO test
  - xctool -scheme "AlamofireSwiftyJSON OSX" -sdk macosx ONLY_ACTIVE_ARCH=NO test
  - xctool -scheme "AlamofireSwiftyJSON watchOS" -sdk watchsimulator ONLY_ACTIVE_ARCH=NO test
  - xctool -scheme "AlamofireSwiftyJSON tvOS" -sdk appletvsimulator ONLY_ACTIVE_ARCH=NO test
  - pod lib lint --allow-warnings
#  - cd demo
#  - carthage update --platform ios
#  - xctool -project carthage.xcodeproj -scheme demo -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
#  - pod install
#  - xctool -workspace pod.xcworkspace -scheme pod -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
