language: objective-c
xcode_project: AlamofireSwiftyJSON.xcodeproj
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
xcode_scheme: AlamofireSwiftyJSON

env:
  matrix:
    - TEST_TYPE=iOS
    - TEST_TYPE=OSX
    - TEST_TYPE=watchOS
    - TEST_TYPE=tvOS

before_install:
- |
    brew install swiftlint
    gem install xcpretty -N --no-ri --no-rdoc
#  - brew update
#  - brew install carthage
#  - gem install cocoapods
install:
- |
    set -o pipefail
    if [ "$TEST_TYPE" = iOS ]; then
      carthage bootstrap --platform iOS
    elif [ "$TEST_TYPE" = OSX ]; then
      carthage bootstrap --platform Mac
    elif [ "$TEST_TYPE" = watchOS ]; then
      carthage bootstrap --platform watchOS
    elif [ "$TEST_TYPE" = tvOS ]; then
      carthage bootstrap --platform tvOS
    fi

script:
- |
    set -o pipefail
    if [ "$TEST_TYPE" = iOS ]; then
      xcodebuild clean test -scheme 'AlamofireSwiftyJSON iOS' -destination "platform=iOS Simulator,name=iPhone 6 Plus" -sdk iphonesimulator -enableCodeCoverage YES  ONLY_ACTIVE_ARCH=NO | xcpretty
      git -C ~/.cocoapods/repos/master/ pull
      pod lib lint --allow-warnings --no-clean
    elif [ "$TEST_TYPE" = OSX ]; then
      xctool -scheme "AlamofireSwiftyJSON OSX" -sdk macosx ONLY_ACTIVE_ARCH=NO test
    elif [ "$TEST_TYPE" = watchOS ]; then
      xctool -scheme "AlamofireSwiftyJSON watchOS" -sdk watchsimulator ONLY_ACTIVE_ARCH=NO test
    elif [ "$TEST_TYPE" = tvOS ]; then
      xctool -scheme "AlamofireSwiftyJSON tvOS" -sdk appletvsimulator ONLY_ACTIVE_ARCH=NO test
    fi

#  - cd demo
#  - carthage update --platform ios
#  - xctool -project carthage.xcodeproj -scheme demo -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
#  - pod install
#  - xctool -workspace pod.xcworkspace -scheme pod -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
after_success:
  - bash <(curl -s https://codecov.io/bash)
